POST localhost:8080/signUp
Content-Type: application/json

{
  "username": "densh2001",
  "password": "123"
}

###

POST localhost:8080/signUp
Content-Type: application/json

{
  "username": "densh2002",
  "password": "123"
}

###

POST localhost:8080/signIn
Content-Type: application/json

{
  "username": "densh2001",
  "password": "123"
}

###

POST localhost:8080/signIn
Content-Type: application/json

{
  "username": "densh2002",
  "password": "123"
}

###

POST localhost:8080/digests/add
Content-Type: application/json
Access: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjM4NzQ0MTM3LCJleHAiOjE2Mzg4NDQxMzd9.cqtLVCDFZV45Ko3mQU_Rf2jlySZTl4ujFcLrnS7EHlU

{
  "filmName": "Harry Potter",
  "text": "user1 review"
}

###

POST localhost:8080/digests/add
Content-Type: application/json
Access: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjM4NzAyMDU5LCJleHAiOjE2Mzg4MDIwNTl9.ZFhvNfrTgLTD07DHTKxUVZUER68Cuao50eK5wr3RFWA

{
  "filmName": "fnewrbvpwrebw",
  "text": "user2 review"
}

###

POST localhost:8080/digests/add
Content-Type: application/json
Access: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjM4NzAyMDU5LCJleHAiOjE2Mzg4MDIwNTl9.ZFhvNfrTgLTD07DHTKxUVZUER68Cuao50eK5wr3RFWA

{
"filmName": "Harry Potter",
"text": "user2 review"
}

###

GET localhost:8080/digests
Access: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjM4NTQ3OTE2LCJleHAiOjE2Mzg2NDc5MTZ9.edzgvQQtPOrluGNd2ZZmKSc59gL_pY5IRn1Xoge0IkQ

###

GET localhost:8080/digests/61ad4067e761cf290b8efad2
Access: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjM4NTQ3OTE2LCJleHAiOjE2Mzg2NDc5MTZ9.edzgvQQtPOrluGNd2ZZmKSc59gL_pY5IRn1Xoge0IkQ

###

PUT localhost:8080/digests/refactor/61ac9c0ff1f5bf2093683e70
Content-Type: application/json
Access: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjM4NzAyMDU5LCJleHAiOjE2Mzg4MDIwNTl9.ZFhvNfrTgLTD07DHTKxUVZUER68Cuao50eK5wr3RFWA

{
  "filmName": "",
  "text": "refactored user2 review"
}

###

DELETE localhost:8080/digests/delete/61aa440d5d225573af832bd0
Access: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjM4NTQ3OTE2LCJleHAiOjE2Mzg2NDc5MTZ9.edzgvQQtPOrluGNd2ZZmKSc59gL_pY5IRn1Xoge0IkQ